#!/usr/bin/env python3
"""Bakes a visualizer.coffee shot JSON into a header the emulator's sim
plays back sample for sample.

Usage:
  curl -s https://visualizer.coffee/api/shots/<id>/download > shot.json
  python3 visualizer_to_header.py shot.json > ../host/shot_data.h
"""
import json
import sys


def main():
    d = json.load(open(sys.argv[1]))
    data = d["data"]
    tf = [float(x) for x in d["timeframe"]]
    pressure = [float(x) for x in data["espresso_pressure"]]
    flow = [float(x) for x in data["espresso_flow"]]
    pgoal = [float(x) for x in data["espresso_pressure_goal"]]
    fgoal = [float(x) for x in data["espresso_flow_goal"]]
    weight = [float(x) for x in data["espresso_weight"]]
    temp = [float(x) for x in data["espresso_temperature_basket"]]

    # preinfusion ends when the cup starts filling
    pour_start = next((i for i, v in enumerate(weight) if v > 0.5), len(weight) // 3)

    # frames advance on sustained goal shifts, ignoring ramp samples
    frames = [0] * len(tf)
    frame = 0
    last_jump = -10
    for i in range(1, len(tf)):
        if abs(pgoal[i] - pgoal[i - 1]) > 0.5 or abs(fgoal[i] - fgoal[i - 1]) > 0.5:
            if i - last_jump > 5:
                frame += 1
            last_jump = i
        frames[i] = frame

    def arr(name, values, fmt):
        vals = ", ".join(fmt % v for v in values)
        print(f"const float shot_{name}[] = {{{vals}}};")

    print("// generated by visualizer_to_header.py, do not edit!")
    print(f"// shot {d.get('id')} \"{d.get('profile_title')}\" {d.get('duration')}s")
    print()
    print(f"const int shot_sample_count = {len(tf)};")
    print(f"const int shot_pour_start_index = {pour_start};")
    arr("time", tf, "%.3ff")
    arr("pressure", pressure, "%.2ff")
    arr("flow", flow, "%.2ff")
    arr("pressure_goal", pgoal, "%.2ff")
    arr("flow_goal", fgoal, "%.2ff")
    arr("weight", weight, "%.2ff")
    arr("temp", temp, "%.1ff")
    ints = ", ".join(str(v) for v in frames)
    print(f"const int shot_frame[] = {{{ints}}};")


if __name__ == "__main__":
    main()
