name: Firmware release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Extract build version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Run PlatformIO
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        run: pio run

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: .pio/build/**/gnat*.bin

      - name: Set up gh-pages files
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          cp -R .pio/build/gh-pages/assets .
          cp -R .pio/build/gh-pages/_releases .
          
      - name: Upload to gh-pages branch
        uses: EndBug/add-and-commit@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          new_branch: gh-pages
          add: '["assets/*", "_releases/*"]'
        
